apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-models-app
  namespace: models-sample-app
  labels:
    app: modeldemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modeldemo
  template:
    metadata:
      labels:
        app: modeldemo
    spec:
     containers:
       - name: model-image
         image: 
         ports:
           - containerPort: 80
         imagePullPolicy: Always
